apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: cards-against-formality-services
build:
  artifacts:
    - image: admin-gateway-service
      context: services/admin-gateway-service
      docker:
        dockerfile: dev.Dockerfile
    - image: web-gateway-service
      context: services/web-gateway-service
      docker:
        dockerfile: dev.Dockerfile
    - image: websocket-gateway-service
      context: services/websocket-gateway-service
      docker:
        dockerfile: dev.Dockerfile
deploy:
  kubectl:
    manifests:
      - config/secret.yaml
      - config/base-config.yaml
      - services/admin-gateway-service/k8s-pod.yaml
      - services/web-gateway-service/k8s-pod.yaml
      - services/websocket-gateway-service/k8s-pod.yaml
  helm:
    releases:
      - name: nats
        chartPath: bitnami/nats
        remote: true
        setValues: { auth.enabled: false }
      - name: websocket-redis
        chartPath: bitnami/redis
        remote: true
        setValues: { usePassword: false }
