apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: cards-against-formality-services
build:
  tagPolicy:
    dateTime:
      format: "2006-01-02_15-04-05.999_MST"
      timezone: "Local"
  artifacts:
    - image: admin-gateway-service
      context: services/admin-gateway-service
      docker:
        dockerfile: dev.Dockerfile
    - image: web-gateway-service
      context: services/web-gateway-service
      docker:
        dockerfile: dev.Dockerfile
    - image: websocket-gateway-service
      context: services/websocket-gateway-service
      docker:
        dockerfile: dev.Dockerfile
    - image: cards-service
      context: services/cards-service
      docker:
        dockerfile: dev.Dockerfile
    - image: decks-service
      context: services/decks-service
      docker:
        dockerfile: dev.Dockerfile
    - image: clients-service
      context: services/clients-service
      docker:
        dockerfile: dev.Dockerfile
    - image: rooms-service
      context: services/rooms-service
      docker:
        dockerfile: dev.Dockerfile
    - image: games-service
      context: services/games-service
      docker:
        dockerfile: dev.Dockerfile
    - image: nginx-gateway
      context: services/nginx
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - config/secret.yaml
      - config/base-config.yaml
      - services/admin-gateway-service/k8s-pod.yaml
      - services/admin-gateway-service/k8s-svc.yaml
      - services/web-gateway-service/k8s-pod.yaml
      - services/web-gateway-service/k8s-svc.yaml
      - services/websocket-gateway-service/k8s-pod.yaml
      - services/websocket-gateway-service/k8s-svc.yaml
      - services/cards-service/k8s-pod.yaml
      - services/cards-service/k8s-svc.yaml
      - services/decks-service/k8s-pod.yaml
      - services/decks-service/k8s-svc.yaml
      - services/clients-service/k8s-pod.yaml
      - services/clients-service/k8s-svc.yaml
      - services/rooms-service/k8s-pod.yaml
      - services/rooms-service/k8s-svc.yaml
      - services/games-service/k8s-pod.yaml
      - services/games-service/k8s-svc.yaml
      - services/nginx/k8s-pod.yaml
      - services/nginx/k8s-svc.yaml
  helm:
    releases:
      - name: nats
        chartPath: bitnami/nats
        remote: true
        setValues: { auth.enabled: false }
      - name: redis
        chartPath: bitnami/redis
        remote: true
        setValues: { usePassword: false }
      - name: mongo
        chartPath: bitnami/mongodb
        remote: true
        setValues: { usePassword: false }
