apiVersion: v1
kind: Service
metadata:
  labels:
    app: websocket-gateway-service
  name: websocket-gateway-service
  annotations: null
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: websocket-gateway-service
