apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx-gateway
  name: nginx-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-gateway
  template:
    metadata:
      labels:
        app: nginx-gateway
    spec:
      containers:
        - name: nginx-gateway
          image: nginx-gateway
          envFrom:
            - configMapRef:
                name: base-config
          ports:
            - containerPort: 80
      restartPolicy: Always
