apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
data:
  NODE_ENV: development
  TRANSPORTER_URI: nats://nats-client.default.svc.cluster.local:4222
  MONGO_URI: mongodb://mongo-mongodb.default.svc.cluster.local:27017
