apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: external-ip-address
    networking.gke.io/managed-certificates: main-certificate
spec:
  defaultBackend:
    service:
      name: nginx-gateway
      port:
        number: 80
