apiVersion: v1
kind: Service
metadata:
  labels:
    app: clients-service
  name: clients-service
  namespace: default
  annotations: null
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: clients-service
