apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: clients-service
  name: clients-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clients-service
  template:
    metadata:
      labels:
        app: clients-service
    spec:
      containers:
        - name: clients-service
          image: clients-service
          envFrom:
            - configMapRef:
                name: base-config
          env:
            - name: PORT
              value: "80"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-auth
                  key: jwtSecret
      restartPolicy: Always
