apiVersion: v1
kind: Pod
metadata:
  name: admin-gateway-service
spec:
  containers:
    - name: admin-gateway-service
      image: admin-gateway-service
      envFrom:
        - configMapRef:
            name: base-config
      env:
        - name: PORT
          value: "80"
        - name: REQUESTS_PER_MINUTE
          value: "100"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-auth
              key: jwtSecret
