apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cards-service
  name: cards-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards-service
  template:
    metadata:
      labels:
        app: cards-service
    spec:
      containers:
        - name: cards-service
          image: cards-service
          envFrom:
            - configMapRef:
                name: base-config
          env:
            - name: PORT
              value: "80"
      restartPolicy: Always
